config/routes.rb
MotCacheV2::Application.routes.draw do

  resources :grilles
  resources :lexiques
  resources :search_lexiques

end

app/models/lexique.rb
class Lexique < ActiveRecord::Base

  before_save :init_lenght
  
  def init_lenght
    self.nbr_lettre = self.mot.length
  end

  def self.search(search, page)
    paginate :per_page => 5, :page => page,
             :conditions => ['mot like ?', "%#{search}%"], :order => 'mot asc'
  end

  def self.obtenir_liste_mot(ids)
    liste = []
    lexiques = Lexique.order('mot asc').find(ids.split(','))
    lexiques.each {|lexique| liste << lexique.mot}
    liste
  end
end

app/controllers/lexiques_controller.rb
class LexiquesController < ApplicationController
  before_action :set_lexique, only: [:show, :edit, :update, :destroy]

  # GET /lexiques
  # GET /lexiques.json
  def index
    @lexiques = Lexique.search(params[:search], params[:page])
    #@lexiques = Lexique.paginate(:per_page => 20, :page => params[:page], :order => "mot asc")
  end

#  GET /lexiques/1
#  GET /lexiques/1.json
  def show
  end

  # GET /lexiques/new
  def new
    @lexique = Lexique.new
  end

  # GET /lexiques/1/edit
  def edit
  end

#  POST /lexiques
#  POST /lexiques.json
  def create
    @lexique = Lexique.new(lexique_params)

    respond_to do |format|
      if @lexique.save
        format.html { redirect_to @lexique, notice: 'Lexique was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lexique }
      else
        format.html { render action: 'new' }
        format.json { render json: @lexique.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lexiques/1
  # PATCH/PUT /lexiques/1.json
  def update
    respond_to do |format|
      if @lexique.update(lexique_params)
        format.html { redirect_to @lexique, notice: 'Lexique was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lexique.errors, status: :unprocessable_entity }
      end
    end
  end

#  DELETE /lexiques/1
#  DELETE /lexiques/1.json
  def destroy
    @lexique.destroy
    respond_to do |format|
      format.html { redirect_to lexiques_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lexique
      @lexique = Lexique.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lexique_params
      params.require(:lexique).permit(:id,:mot,:nbr_lettre)
    end
end

app/helpers/lexiques_helper.rb
module LexiquesHelper
end

app/views/lexiques/_form.html.erb
<%= form_for(@lexique) do |f| %>
  <% if @lexique.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lexique.errors.count, "error") %> prohibited this lexique from being saved:</h2>

      <ul>
      <% @lexique.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
        <%= f.label :mot %><br />
        <%= f.text_field :mot %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lexiques/_lexiques.html.erb
<%= will_paginate @lexiques %>

<% for lexique in @lexiques %>
    <div class="lexique">
      <h3>
        <%= link_to h(lexique.mot), lexique %>
      </h3>
      <div class="actions">
        <%= link_to 'Edit', edit_lexique_path(lexique) %>
        <%= link_to 'Destroy', lexique, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
<% end %>
<%= will_paginate @lexiques %>

app/views/lexiques/edit.html.erb
<h1>Editing lexique</h1>

<%= render 'form' %>

<%= link_to 'Show', @lexique %> |
<%= link_to 'Back', lexiques_path %>

app/views/lexiques/index.html.erb
<h1>Listing lexiques</h1>



<%= form_tag lexiques_path, :method => 'get', :id => "lexiques_search" do %>
    <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil %>
    </p>
    <div id="lexiques">
        <%= render 'lexiques' %>
    </div>
<% end %>


<%= link_to 'New Lexique', new_lexique_path %>

app/views/lexiques/index.js.erb
//alert("ceci est une demande ajax!");
$("#lexiques").html("<%= escape_javascript(render("lexiques"))%>");
// #lexiques est le div

app/views/lexiques/new.html.erb
<h1>New lexique</h1>

<%= render 'form' %>

<%= link_to 'Back', lexiques_path %>

app/views/lexiques/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_lexique_path(@lexique) %> |
<%= link_to 'Back', lexiques_path %>